#include "matrix/Matrix.cuh"
#include "matrix/Matrix.hxx"

template class Matrix<1, 2>;
template class Matrix<1, 3>;
template class Matrix<1, 4>;
template class Matrix<1, 5>;
template class Matrix<1, 6>;
template class Matrix<1, 7>;
template class Matrix<1, 8>;
template class Matrix<1, 9>;
template class Matrix<1, 10>;
template class Matrix<1, 11>;
template class Matrix<1, 12>;
template class Matrix<1, 13>;
template class Matrix<1, 14>;
template class Matrix<2, 1>;
template class Matrix<2, 2>;
template class Matrix<2, 3>;
template class Matrix<2, 4>;
template class Matrix<2, 5>;
template class Matrix<2, 6>;
template class Matrix<2, 7>;
template class Matrix<2, 8>;
template class Matrix<2, 9>;
template class Matrix<2, 10>;
template class Matrix<2, 11>;
template class Matrix<2, 12>;
template class Matrix<2, 13>;
template class Matrix<2, 14>;
template class Matrix<3, 2>;
template class Matrix<3, 3>;
template class Matrix<3, 4>;
template class Matrix<3, 5>;
template class Matrix<3, 6>;
template class Matrix<3, 7>;
template class Matrix<3, 8>;
template class Matrix<3, 9>;
template class Matrix<3, 10>;
template class Matrix<3, 11>;
template class Matrix<3, 12>;
template class Matrix<3, 13>;
template class Matrix<3, 14>;
template class Matrix<4, 2>;
template class Matrix<4, 3>;
template class Matrix<4, 4>;
template class Matrix<4, 5>;
template class Matrix<4, 6>;
template class Matrix<4, 7>;
template class Matrix<4, 8>;
template class Matrix<4, 9>;
template class Matrix<4, 10>;
template class Matrix<4, 11>;
template class Matrix<4, 12>;
template class Matrix<4, 13>;
template class Matrix<4, 14>;
template class Matrix<5, 2>;
template class Matrix<5, 3>;
template class Matrix<5, 4>;
template class Matrix<5, 5>;
template class Matrix<5, 6>;
template class Matrix<5, 7>;
template class Matrix<5, 8>;
template class Matrix<5, 9>;
template class Matrix<5, 10>;
template class Matrix<5, 11>;
template class Matrix<5, 12>;
template class Matrix<5, 13>;
template class Matrix<5, 14>;
template class Matrix<6, 2>;
template class Matrix<6, 3>;
template class Matrix<6, 4>;
template class Matrix<6, 5>;
template class Matrix<6, 6>;
template class Matrix<6, 7>;
template class Matrix<6, 8>;
template class Matrix<6, 9>;
template class Matrix<6, 10>;
template class Matrix<6, 11>;
template class Matrix<6, 12>;
template class Matrix<6, 13>;
template class Matrix<6, 14>;
template class Matrix<7, 2>;
template class Matrix<7, 3>;
template class Matrix<7, 4>;
template class Matrix<7, 5>;
template class Matrix<7, 6>;
template class Matrix<7, 7>;
template class Matrix<7, 8>;
template class Matrix<7, 9>;
template class Matrix<7, 10>;
template class Matrix<7, 11>;
template class Matrix<7, 12>;
template class Matrix<7, 13>;
template class Matrix<7, 14>;
template class Matrix<8, 2>;
template class Matrix<8, 3>;
template class Matrix<8, 4>;
template class Matrix<8, 5>;
template class Matrix<8, 6>;
template class Matrix<8, 7>;
template class Matrix<8, 8>;
template class Matrix<8, 9>;
template class Matrix<8, 10>;
template class Matrix<8, 11>;
template class Matrix<8, 12>;
template class Matrix<8, 13>;
template class Matrix<8, 14>;
template class Matrix<9, 2>;
template class Matrix<9, 3>;
template class Matrix<9, 4>;
template class Matrix<9, 5>;
template class Matrix<9, 6>;
template class Matrix<9, 7>;
template class Matrix<9, 8>;
template class Matrix<9, 9>;
template class Matrix<9, 10>;
template class Matrix<9, 11>;
template class Matrix<9, 12>;
template class Matrix<9, 13>;
template class Matrix<9, 14>;
template class Matrix<10, 2>;
template class Matrix<10, 3>;
template class Matrix<10, 4>;
template class Matrix<10, 5>;
template class Matrix<10, 6>;
template class Matrix<10, 7>;
template class Matrix<10, 8>;
template class Matrix<10, 9>;
template class Matrix<10, 10>;
template class Matrix<10, 11>;
template class Matrix<10, 12>;
template class Matrix<10, 13>;
template class Matrix<10, 14>;
template class Matrix<11, 2>;
template class Matrix<11, 3>;
template class Matrix<11, 4>;
template class Matrix<11, 5>;
template class Matrix<11, 6>;
template class Matrix<11, 7>;
template class Matrix<11, 8>;
template class Matrix<11, 9>;
template class Matrix<11, 10>;
template class Matrix<11, 11>;
template class Matrix<11, 12>;
template class Matrix<11, 13>;
template class Matrix<11, 14>;
template class Matrix<12, 2>;
template class Matrix<12, 3>;
template class Matrix<12, 4>;
template class Matrix<12, 5>;
template class Matrix<12, 6>;
template class Matrix<12, 7>;
template class Matrix<12, 8>;
template class Matrix<12, 9>;
template class Matrix<12, 10>;
template class Matrix<12, 11>;
template class Matrix<12, 12>;
template class Matrix<12, 13>;
template class Matrix<12, 14>;
template class Matrix<13, 2>;
template class Matrix<13, 3>;
template class Matrix<13, 4>;
template class Matrix<13, 5>;
template class Matrix<13, 6>;
template class Matrix<13, 7>;
template class Matrix<13, 8>;
template class Matrix<13, 9>;
template class Matrix<13, 10>;
template class Matrix<13, 11>;
template class Matrix<13, 12>;
template class Matrix<13, 13>;
template class Matrix<13, 14>;
template class Matrix<14, 2>;
template class Matrix<14, 3>;
template class Matrix<14, 4>;
template class Matrix<14, 5>;
template class Matrix<14, 6>;
template class Matrix<14, 7>;
template class Matrix<14, 8>;
template class Matrix<14, 9>;
template class Matrix<14, 10>;
template class Matrix<14, 11>;
template class Matrix<14, 12>;
template class Matrix<14, 13>;
template class Matrix<14, 14>;
template class Matrix<3,3,3>;
template class Matrix<1,1,6>;
template class Matrix<3,3,2>;
template class Matrix<1,1,3>;
template class Matrix<2,2,2>;
template class Matrix<3,3,1,false>;
template class Matrix<1,1,2>;
template class Matrix<3,3,3, false>;
template class Matrix<5,2,1, false>;
template class Matrix<1,1,2, false>;
template class Matrix<1,1,6,false>;
template class Matrix<5,1,1,false>;
template class Matrix<5,1,1,true>;
//template class Matrix<5,1,1,true>;
//template class Matrix<2, 1, 1, true>;
//template class Matrix<5, 1, 1, true>;
template class Matrix<2, 1, 1, false>;
//template class Matrix<2, 2, 1, true>;
//template class Matrix<3, 3, 1, true>;
//template class Matrix<4, 4, 1, true>;
template class Matrix<1, 1, 1, true>;